# Generated by Django 4.2 on 2023-05-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Suplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Спортивное питание',
                'verbose_name_plural': 'Спортивное питание',
            },
        ),
    ]
